[mypy]
python_version = 3.12

ignore_missing_imports = True
disallow_untyped_defs = False
check_untyped_defs = False
warn_return_any = False
warn_unused_ignores = False
allow_redefinition = True

exclude = (env|venv|\.venv|migrations|tests|vanna)

[mypy-services.*]
ignore_errors = True

[mypy-vanna.*]
ignore_errors = True

[mypy-langchain_sandbox.*]
ignore_errors = True